def random_string
  (0...8).map{(65+rand(26)).chr}.join
end

puts "Seeding 100 images, subscribers and videos"
100.times do
  Image.create!( title: "Image #{random_string}" )
  Subscriber.create!( title: "Subscriber #{random_string}", description: random_string )
  Video.create!( title: "Video #{random_string}", description: random_string )
end

puts "Seeding 1000 tags"
1000.times do
  Tag.create!( name: "Tag #{random_string}", description: random_string, level: (1..10).to_a.sample )
end

puts "Seeding 243 countries"
Country.create :code =>"AGO", :name => "Angola", :region => "Africa"
Country.create :code =>"BEN", :name => "Benin", :region => "Africa"
Country.create :code =>"BWA", :name => "Botswana", :region => "Africa"
Country.create :code =>"BFA", :name => "Burkina Faso", :region => "Africa"
Country.create :code =>"BDI", :name => "Burundi", :region => "Africa"
Country.create :code =>"CMR", :name => "Cameroon", :region => "Africa"
Country.create :code =>"SPI", :name => "Canary Islands", :region => "Africa"
Country.create :code =>"CPV", :name => "Cape Verde", :region => "Africa"
Country.create :code =>"CAF", :name => "Central African Republic", :region => "Africa"
Country.create :code =>"TCD", :name => "Chad", :region => "Africa"
Country.create :code =>"COM", :name => "Comoros", :region => "Africa"
Country.create :code =>"COG", :name => "Congo", :region => "Africa"
Country.create :code =>"COD", :name => "Congo (Democratic Republic of the)", :region => "Africa"
Country.create :code =>"CIV", :name => "Cote d'Ivoire", :region => "Africa"
Country.create :code =>"DJI", :name => "Djibouti", :region => "Africa"
Country.create :code =>"GNQ", :name => "Equatorial Guinea", :region => "Africa"
Country.create :code =>"ERI", :name => "Eritrea", :region => "Africa"
Country.create :code =>"ETH", :name => "Ethiopia", :region => "Africa"
Country.create :code =>"GAB", :name => "Gabon", :region => "Africa"
Country.create :code =>"GMB", :name => "Gambia", :region => "Africa"
Country.create :code =>"GHA", :name => "Ghana", :region => "Africa"
Country.create :code =>"GIN", :name => "Guinea", :region => "Africa"
Country.create :code =>"GNB", :name => "Guinea-Bissau", :region => "Africa"
Country.create :code =>"KEN", :name => "Kenya", :region => "Africa"
Country.create :code =>"LSO", :name => "Lesotho", :region => "Africa"
Country.create :code =>"MDG", :name => "Madagascar", :region => "Africa"
Country.create :code =>"MWI", :name => "Malawi", :region => "Africa"
Country.create :code =>"MLI", :name => "Mali", :region => "Africa"
Country.create :code =>"MRT", :name => "Mauritania", :region => "Africa"
Country.create :code =>"MUS", :name => "Mauritius", :region => "Africa"
Country.create :code =>"MYT", :name => "Mayotte (France)", :region => "Africa"
Country.create :code =>"MOZ", :name => "Mozambique", :region => "Africa"
Country.create :code =>"NAM", :name => "Namibia", :region => "Africa"
Country.create :code =>"NER", :name => "Niger", :region => "Africa"
Country.create :code =>"NGA", :name => "Nigeria", :region => "Africa"
Country.create :code =>"REU", :name => "Reunion (France)", :region => "Africa"
Country.create :code =>"RWA", :name => "Rwanda", :region => "Africa"
Country.create :code =>"SHN", :name => "Saint Helena", :region => "Africa"
Country.create :code =>"STP", :name => "Sao Tome and Principe", :region => "Africa"
Country.create :code =>"SEN", :name => "Senegal", :region => "Africa"
Country.create :code =>"SYC", :name => "Seychelles", :region => "Africa"
Country.create :code =>"SLE", :name => "Sierra Leone", :region => "Africa"
Country.create :code =>"SOM", :name => "Somalia", :region => "Africa"
Country.create :code =>"ZAF", :name => "South Africa", :region => "Africa"
Country.create :code =>"SDN", :name => "Sudan", :region => "Africa"
Country.create :code =>"SWZ", :name => "Swaziland", :region => "Africa"
Country.create :code =>"TGO", :name => "Togo", :region => "Africa"
Country.create :code =>"UGA", :name => "Uganda", :region => "Africa"
Country.create :code =>"TZA", :name => "United Republic of Tanzania", :region => "Africa"
Country.create :code =>"ESH", :name => "Western Sahara", :region => "Africa"
Country.create :code =>"ZMB", :name => "Zambia", :region => "Africa"
Country.create :code =>"ZWE", :name => "Zimbabwe", :region => "Africa"

Country.create :code =>"AIA", :name => "Anguilla", :region => "Americas"
Country.create :code =>"ATG", :name => "Antigua and Barbuda", :region => "Americas"
Country.create :code =>"ARG", :name => "Argentina", :region => "Americas"
Country.create :code =>"ABW", :name => "Aruba", :region => "Americas"
Country.create :code =>"BHS", :name => "Bahamas", :region => "Americas"
Country.create :code =>"BRB", :name => "Barbados", :region => "Americas"
Country.create :code =>"BLZ", :name => "Belize", :region => "Americas"
Country.create :code =>"BMU", :name => "Bermuda", :region => "Americas"
Country.create :code =>"BOL", :name => "Bolivia", :region => "Americas"
Country.create :code =>"BRA", :name => "Brazil", :region => "Americas"
Country.create :code =>"CAN", :name => "Canada", :region => "Americas"
Country.create :code =>"CYM", :name => "Cayman Islands", :region => "Americas"
Country.create :code =>"CHL", :name => "Chile", :region => "Americas"
Country.create :code =>"COL", :name => "Colombia", :region => "Americas"
Country.create :code =>"CRI", :name => "Costa Rica", :region => "Americas"
Country.create :code =>"CUB", :name => "Cuba", :region => "Americas"
Country.create :code =>"DMA", :name => "Dominica", :region => "Americas"
Country.create :code =>"DOM", :name => "Dominican Republic", :region => "Americas"
Country.create :code =>"HSI", :name => "Easter Island (Chile)", :region => "Americas"
Country.create :code =>"ECU", :name => "Ecuador", :region => "Americas"
Country.create :code =>"SLV", :name => "El Salvador", :region => "Americas"
Country.create :code =>"FLK", :name => "Falkland Islands (Malvinas)", :region => "Americas"
Country.create :code =>"GUF", :name => "French Guiana", :region => "Americas"
Country.create :code =>"ECG", :name => "Galapagos Islands (Ecuador)", :region => "Americas"
Country.create :code =>"GRL", :name => "Greenland", :region => "Americas"
Country.create :code =>"GRD", :name => "Grenada", :region => "Americas"
Country.create :code =>"GLP", :name => "Guadeloupe (France)", :region => "Americas"
Country.create :code =>"GTM", :name => "Guatemala", :region => "Americas"
Country.create :code =>"GUY", :name => "Guyana", :region => "Americas"
Country.create :code =>"HTI", :name => "Haiti", :region => "Americas"
Country.create :code =>"HND", :name => "Honduras", :region => "Americas"
Country.create :code =>"JAM", :name => "Jamaica", :region => "Americas"
Country.create :code =>"MTQ", :name => "Martinique", :region => "Americas"
Country.create :code =>"MEX", :name => "Mexico", :region => "Americas"
Country.create :code =>"MSR", :name => "Montserrat", :region => "Americas"
Country.create :code =>"ANT", :name => "Netherlands Antilles", :region => "Americas"
Country.create :code =>"NIC", :name => "Nicaragua", :region => "Americas"
Country.create :code =>"PAN", :name => "Panama", :region => "Americas"
Country.create :code =>"PRY", :name => "Paraguay", :region => "Americas"
Country.create :code =>"PER", :name => "Peru", :region => "Americas"
Country.create :code =>"PRI", :name => "Puerto Rico", :region => "Americas"
Country.create :code =>"KNA", :name => "Saint Kitts and Nevis", :region => "Americas"
Country.create :code =>"LCA", :name => "Saint Lucia", :region => "Americas"
Country.create :code =>"SPM", :name => "Saint Pierre and Miquelon (France)", :region => "Americas"
Country.create :code =>"VCT", :name => "Saint Vincent and the Grenadines", :region => "Americas"
Country.create :code =>"SUR", :name => "Suriname", :region => "Americas"
Country.create :code =>"TTO", :name => "Trinidad and Tobago", :region => "Americas"
Country.create :code =>"TCA", :name => "Turks and Caicos Islands", :region => "Americas"
Country.create :code =>"USA", :name => "United States", :region => "Americas"
Country.create :code =>"URY", :name => "Uruguay", :region => "Americas"
Country.create :code =>"VEN", :name => "Venezuela", :region => "Americas"
Country.create :code =>"VGB", :name => "Virgin Islands (British)", :region => "Americas"
Country.create :code =>"VIR", :name => "Virgin Islands (United States)", :region => "Americas"

Country.create :code =>"AFG", :name => "Afghanistan", :region => "Asia"
Country.create :code =>"ARM", :name => "Armenia", :region => "Asia"
Country.create :code =>"AZE", :name => "Azerbaijan", :region => "Asia"
Country.create :code =>"BGD", :name => "Bangladesh", :region => "Asia"
Country.create :code =>"BTN", :name => "Bhutan", :region => "Asia"
Country.create :code =>"BVT", :name => "Brunei Darussalam", :region => "Asia"
Country.create :code =>"KHM", :name => "Cambodia", :region => "Asia"
Country.create :code =>"CHN", :name => "China", :region => "Asia"
Country.create :code =>"CXR", :name => "Christmas Island", :region => "Asia"
Country.create :code =>"CCK", :name => "Cocos (Keeling) Islands", :region => "Asia"
Country.create :code =>"CYP", :name => "Cyprus", :region => "Asia"
Country.create :code =>"PRK", :name => "Democratic People's Republic of Korea", :region => "Asia"
Country.create :code =>"ATF", :name => "French Southern and Antarctic Lands", :region => "Asia"
Country.create :code =>"GEO", :name => "Georgia", :region => "Asia"
Country.create :code =>"HKG", :name => "China - Hong Kong (Special Administrative Region)", :region => "Asia"
Country.create :code =>"IND", :name => "India", :region => "Asia"
Country.create :code =>"IDN", :name => "Indonesia", :region => "Asia"
Country.create :code =>"JPN", :name => "Japan", :region => "Asia"
Country.create :code =>"KAZ", :name => "Kazakhstan", :region => "Asia"
Country.create :code =>"KGZ", :name => "Kyrgyzstan", :region => "Asia"
Country.create :code =>"LAO", :name => "Lao People's Democratic Republic", :region => "Asia"
Country.create :code =>"MAC", :name => "China - Macau (Special Administrative Region)", :region => "Asia"
Country.create :code =>"MYS", :name => "Malaysia", :region => "Asia"
Country.create :code =>"MDV", :name => "Maldives", :region => "Asia"
Country.create :code =>"MNG", :name => "Mongolia", :region => "Asia"
Country.create :code =>"MMR", :name => "Myanmar", :region => "Asia"
Country.create :code =>"NPL", :name => "Nepal", :region => "Asia"
Country.create :code =>"PSE", :name => "Occupied Palestinian Territory", :region => "Asia"
Country.create :code =>"PAK", :name => "Pakistan", :region => "Asia"
Country.create :code =>"PHL", :name => "Philippines", :region => "Asia"
Country.create :code =>"KOR", :name => "Republic of Korea", :region => "Asia"
Country.create :code =>"SGP", :name => "Singapore", :region => "Asia"
Country.create :code =>"LKA", :name => "Sri Lanka", :region => "Asia"
Country.create :code =>"TWN", :name => "China - Taiwan Province", :region => "Asia"
Country.create :code =>"TJK", :name => "Tajikistan", :region => "Asia"
Country.create :code =>"THA", :name => "Thailand", :region => "Asia"
Country.create :code =>"TLS", :name => "Timor Leste", :region => "Asia"
Country.create :code =>"TUR", :name => "Turkey", :region => "Asia"
Country.create :code =>"TKM", :name => "Turkmenistan", :region => "Asia"
Country.create :code =>"UZB", :name => "Uzbekistan", :region => "Asia"
Country.create :code =>"VNM", :name => "Vietnam", :region => "Asia"

Country.create :code =>"ALA", :name => "Aland Islands (Finland)", :region => "Europe"
Country.create :code =>"ALB", :name => "Albania", :region => "Europe"
Country.create :code =>"AND", :name => "Andorra", :region => "Europe"
Country.create :code =>"AUT", :name => "Austria", :region => "Europe"
Country.create :code =>"AZR", :name => "Azores", :region => "Europe"
Country.create :code =>"BLR", :name => "Belarus", :region => "Europe"
Country.create :code =>"BEL", :name => "Belgium", :region => "Europe"
Country.create :code =>"BIH", :name => "Bosnia and Herzegovina", :region => "Europe"
Country.create :code =>"BGR", :name => "Bulgaria", :region => "Europe"
Country.create :code =>"GG", :name => "Channel Islands", :region => "Europe"
Country.create :code =>"HRV", :name => "Croatia", :region => "Europe"
Country.create :code =>"CZE", :name => "Czech Republic", :region => "Europe"
Country.create :code =>"DNK", :name => "Denmark", :region => "Europe"
Country.create :code =>"EST", :name => "Estonia", :region => "Europe"
Country.create :code =>"FRO", :name => "Faeroe Islands", :region => "Europe"
Country.create :code =>"FIN", :name => "Finland", :region => "Europe"
Country.create :code =>"FRA", :name => "France", :region => "Europe"
Country.create :code =>"DEU", :name => "Germany", :region => "Europe"
Country.create :code =>"GIB", :name => "Gibraltar", :region => "Europe"
Country.create :code =>"GRC", :name => "Greece", :region => "Europe"
Country.create :code =>"VAT", :name => "Holy See", :region => "Europe"
Country.create :code =>"HUN", :name => "Hungary", :region => "Europe"
Country.create :code =>"ISL", :name => "Iceland", :region => "Europe"
Country.create :code =>"IRL", :name => "Ireland", :region => "Europe"
Country.create :code =>"IM", :name => "Isle of Man", :region => "Europe"
Country.create :code =>"ITA", :name => "Italy", :region => "Europe"
Country.create :code =>"LVA", :name => "Latvia", :region => "Europe"
Country.create :code =>"LIE", :name => "Liechtenstein", :region => "Europe"
Country.create :code =>"LTU", :name => "Lithuania", :region => "Europe"
Country.create :code =>"LUX", :name => "Luxembourg", :region => "Europe"
Country.create :code =>"MI", :name => "Madeira (Portugal)", :region => "Europe"
Country.create :code =>"MLT", :name => "Malta", :region => "Europe"
Country.create :code =>"MCO", :name => "Monaco", :region => "Europe"
Country.create :code =>"MTN", :name => "Montenegro", :region => "Europe"
Country.create :code =>"NLD", :name => "Netherlands", :region => "Europe"
Country.create :code =>"NOR", :name => "Norway", :region => "Europe"
Country.create :code =>"POL", :name => "Poland", :region => "Europe"
Country.create :code =>"PRT", :name => "Portugal", :region => "Europe"
Country.create :code =>"MDA", :name => "Republic of Moldova", :region => "Europe"
Country.create :code =>"ROU", :name => "Romania", :region => "Europe"
Country.create :code =>"RUS", :name => "Russian Federation", :region => "Europe"
Country.create :code =>"SMR", :name => "San Marino", :region => "Europe"
Country.create :code =>"SCG", :name => "Serbia", :region => "Europe"
Country.create :code =>"SVK", :name => "Slovakia", :region => "Europe"
Country.create :code =>"SVN", :name => "Slovenia", :region => "Europe"
Country.create :code =>"ESP", :name => "Spain", :region => "Europe"
Country.create :code =>"SJM", :name => "Svalbard and Jan Mayen Islands (Norway)", :region => "Europe"
Country.create :code =>"SWE", :name => "Sweden", :region => "Europe"
Country.create :code =>"CHE", :name => "Switzerland", :region => "Europe"
Country.create :code =>"MKD", :name => "The former Yugoslav Republic of Macedonia", :region => "Europe"
Country.create :code =>"UKR", :name => "Ukraine", :region => "Europe"
Country.create :code =>"GBR", :name => "United Kingdom", :region => "Europe"

Country.create :code =>"DZA", :name => "Algeria", :region => "Middle East"
Country.create :code =>"BHR", :name => "Bahrain", :region => "Middle East"
Country.create :code =>"EGY", :name => "Egypt", :region => "Middle East"
Country.create :code =>"IRN", :name => "Iran", :region => "Middle East"
Country.create :code =>"IRQ", :name => "Iraq", :region => "Middle East"
Country.create :code =>"ISR", :name => "Israel", :region => "Middle East"
Country.create :code =>"JOR", :name => "Jordan", :region => "Middle East"
Country.create :code =>"KWT", :name => "Kuwait", :region => "Middle East"
Country.create :code =>"LBN", :name => "Lebanon", :region => "Middle East"
Country.create :code =>"LBR", :name => "Liberia", :region => "Middle East"
Country.create :code =>"LBY", :name => "Libyan Arab Jamahiriya", :region => "Middle East"
Country.create :code =>"MAR", :name => "Morocco", :region => "Middle East"
Country.create :code =>"OMN", :name => "Oman", :region => "Middle East"
Country.create :code =>"QAT", :name => "Qatar", :region => "Middle East"
Country.create :code =>"SAU", :name => "Saudi Arabia", :region => "Middle East"
Country.create :code =>"SYR", :name => "Syrian Arab Republic", :region => "Middle East"
Country.create :code =>"TUN", :name => "Tunisia", :region => "Middle East"
Country.create :code =>"ARE", :name => "United Arab Emirates", :region => "Middle East"
Country.create :code =>"YEM", :name => "Yemen", :region => "Middle East"

Country.create :code =>"ASM", :name => "American Samoa", :region => "Oceania"
Country.create :code =>"AUS", :name => "Australia", :region => "Oceania"
Country.create :code =>"COK", :name => "Cook Islands", :region => "Oceania"
Country.create :code =>"FJI", :name => "Fiji", :region => "Oceania"
Country.create :code =>"PYF", :name => "French Polynesia", :region => "Oceania"
Country.create :code =>"GUM", :name => "Guam", :region => "Oceania"
Country.create :code =>"HMD", :name => "Heard and McDonald Islands", :region => "Oceania"
Country.create :code =>"KIR", :name => "Kiribati", :region => "Oceania"
Country.create :code =>"MHL", :name => "Marshall Islands", :region => "Oceania"
Country.create :code =>"FSM", :name => "Micronesia (Federated States of)", :region => "Oceania"
Country.create :code =>"NRU", :name => "Nauru", :region => "Oceania"
Country.create :code =>"NCL", :name => "New Caledonia", :region => "Oceania"
Country.create :code =>"NZL", :name => "New Zealand", :region => "Oceania"
Country.create :code =>"NIU", :name => "Niue", :region => "Oceania"
Country.create :code =>"NFK", :name => "Norfolk Island", :region => "Oceania"
Country.create :code =>"MNP", :name => "Northern Mariana Islands", :region => "Oceania"
Country.create :code =>"PLW", :name => "Palau", :region => "Oceania"
Country.create :code =>"PNG", :name => "Papua New Guinea", :region => "Oceania"
Country.create :code =>"PCN", :name => "Pitcairn", :region => "Oceania"
Country.create :code =>"WSM", :name => "Samoa", :region => "Oceania"
Country.create :code =>"SLB", :name => "Solomon Islands", :region => "Oceania"
Country.create :code =>"TKL", :name => "Tokelau", :region => "Oceania"
Country.create :code =>"TON", :name => "Tonga", :region => "Oceania"
Country.create :code =>"TUV", :name => "Tuvalu", :region => "Oceania"
Country.create :code =>"VUT", :name => "Vanuatu", :region => "Oceania"
Country.create :code =>"WLF", :name => "Wallis and Futuna Islands", :region => "Oceania"

ThinkingSphinx::Deltas.suspend!
puts "Seeding 300 documents"
300.times do |i|
  country_ids = Country.select(:id).map(&:id)
  image_ids = Image.select(:id).map(&:id)
  subscriber_ids = Subscriber.select(:id).map(&:id)
  video_ids = Video.select(:id).map(&:id)
  tag_ids = Tag.select(:id).map(&:id)

  Document.create!(
        title: (0...8).map{(65+rand(26)).chr}.join,
        country_ids:    country_ids.sample(50),
        image_ids:      image_ids.sample(50),
        subscriber_ids: subscriber_ids.sample(50),
        video_ids:      video_ids.sample(50),
        tag_ids:        tag_ids.sample(50)
  )
end
ThinkingSphinx::Deltas.resume!
